"""teste

Revision ID: 529ff2d5597a
Revises: 5971d179dc7c
Create Date: 2024-05-25 08:14:41.852529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529ff2d5597a'
down_revision: Union[str, None] = '5971d179dc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividades', sa.Column('descricao', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atividades', 'descricao')
    # ### end Alembic commands ###
