"""Sua

Revision ID: 5971d179dc7c
Revises: 5c18a00bcc0d
Create Date: 2024-05-25 05:31:30.987515

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5971d179dc7c'
down_revision: Union[str, None] = '5c18a00bcc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('atividades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_atividade',
    sa.Column('aluno_id', sa.String(length=36), nullable=True),
    sa.Column('atividade_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.UniqueConstraint('aluno_id', 'atividade_id', name='uix_aluno_atividade')
    )
    op.create_table('grupo_atividade',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('atividade_id', sa.String(length=36), nullable=True),
    sa.Column('sequencia_pontuacao', sa.Integer(), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('gabarito', sa.String(length=300), nullable=False),
    sa.Column('enunciado', sa.String(length=300), nullable=True),
    sa.Column('id_atividade', sa.String(length=36), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_atividade'], ['atividades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_aluno',
    sa.Column('grupo_id', sa.String(length=36), nullable=True),
    sa.Column('aluno_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_atividade.id'], ),
    sa.UniqueConstraint('grupo_id', 'aluno_id', name='uix_grupo_aluno')
    )
    op.create_table('respostas_aluno',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resposta', sa.String(length=300), nullable=False),
    sa.Column('questao_id', sa.String(length=36), nullable=True),
    sa.Column('aluno_id', sa.String(length=36), nullable=True),
    sa.Column('atividade_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'CORRETA', 'INCORRETA', name='statusresposta'), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas_aluno')
    op.drop_table('grupo_aluno')
    op.drop_table('questoes')
    op.drop_table('grupo_atividade')
    op.drop_table('aluno_atividade')
    op.drop_table('atividades')
    op.drop_table('alunos')
    # ### end Alembic commands ###
