"""Sua mensagem de migração aqui

Revision ID: 5c18a00bcc0d
Revises: 17a999db3fb5
Create Date: 2024-05-25 05:11:47.769464

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c18a00bcc0d'
down_revision: Union[str, None] = '17a999db3fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
